import { Module } from '@nestjs/common';
import { GraphQLModule } from '@nestjs/graphql';
import { MercuriusDriver, MercuriusDriverConfig } from '@nestjs/mercurius';
import path from 'path';

import { AppController } from './app.controller';
import { AppService } from './app.service';

@Module({
  imports: [GraphQLModule.forRoot<MercuriusDriverConfig>({
    driver: MercuriusDriver,
    autoSchemaFile: path.join(__dirname, './autogenerated-schema.gql'),
    graphiql: true
  }),],
  controllers: [AppController],
  providers: [AppService],
})
export class AppModule { }
